<h2>Contact Us</h2>

<div class="row">
    <form method="post">
    
        <div class="col-md-12 form-group">
            <label for="">Firstname</label>
            <input class="form-control" type="text" name="firstname"/>
        </div>
        
        <div class="col-md-12 form-group">
            <label for="">Lastname</label>
            <input class="form-control" type="text" name="lastname"/>
        </div>
    
        <div class="col-md-12 form-group">
            <label for="">Email</label>
            <input class="form-control" type="email" name="email"/>
        </div>
        
        <div class="col-md-12 form-group">
            <label for="">Message</label>
            <textarea class="form-control" type="text" name="message"></textarea>
        </div>
        
        <button class="col-md-12 btn btn-primary mt-3" type="submit">Sent</button>
        
    </form>
</div>