<h1>Ma page d'accueil de mon super blog</h1>

<section>
    
    <h2 style="text-align: center">Nos articles populaires</h2>
    
    <div class="row">
        <?php foreach($data["products"] as $row) {?>
            <div class="col-md-3">
                <div class="card">
                  <img class="card-img-top" src="<?php echo $row->image; ?>" alt="Card image cap">
                  <div class="card-body">
                    <h5 class="card-title"><?php echo $row->name; ?></h5>
                    <p class="card-text"><?php echo substr($row->description, 0, 100); ?>...</p>
                    <a href="product/<?php echo $row->id; ?>" class="btn btn-primary">See more</a>
                  </div>
                </div>
            </div>
        <?php } ?>
    </div>
</section>