<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>MVC Project</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.1.3/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://bootswatch.com/_vendor/bootstrap/dist/css/bootstrap.min.css">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
      <div class="container-fluid">
        <a class="navbar-brand" href="https://valentinragot.sites.3wa.io/php_avance/mvc/">MVC Project</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
    
        <div class="collapse navbar-collapse" id="navbarColor01">
          <ul class="navbar-nav me-auto">
            <li class="nav-item"><a class="nav-link" href="https://valentinragot.sites.3wa.io/php_avance/mvc/">Home</a></li>
            <li class="nav-item"><a class="nav-link" href="https://valentinragot.sites.3wa.io/php_avance/mvc/products">Products</a></li>
            <li class="nav-item"><a class="nav-link" href="https://valentinragot.sites.3wa.io/php_avance/mvc/contact">Contact</a></li>
            <li class="nav-item"><a class="nav-link" href="https://valentinragot.sites.3wa.io/php_avance/mvc/basket">Basket</a></li>
          </ul>
          <div class="d-flex">
            <?php if(!empty($data["modules"]["auth"]->get_session())){?>
              <div class="dropdown">
                <button class="btn btn-secondary dropdown-toggle" data-bs-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">My Account</button>
                <div class="dropdown-menu">
                  <a class="dropdown-item" href="https://valentinragot.sites.3wa.io/php_avance/mvc/settings">Settings</a>
                  <a class="dropdown-item" href="https://valentinragot.sites.3wa.io/php_avance/mvc/purchases">My purchases</a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="https://valentinragot.sites.3wa.io/php_avance/mvc/logout">Log Out</a>
                </div>
              </div>
            <?php }else{ ?>
              <a class="btn btn-secondary" href="https://valentinragot.sites.3wa.io/php_avance/mvc/login">Log In</a>
            <?php } ?>
          </div>
        </div>
      </div>
    </nav>
    <div class="container mt-5">
      <div class="row">
        
        <?php if(isset($data["flashMessage"])) {?>
          <div class="alert alert-<?php echo $data["flashMessage"]["type"]; ?>">
            <?php echo $data["flashMessage"]["message"]; ?>
          </div>
        <?php } ?>
        
        
        <?php include $template ?>
      </div>
    </div>
    
    <footer class="bg-primary text-white mt-5 pt-5 pb-5">
      <p style="text-align:center">Copyright - <?php echo $date; ?></p>
    </footer>

</body>
</html>