
<form method="post">

    <div class="col-md-12 form-group">
        <label for="">Email</label>
        <input class="form-control" type="email" name="email"/>
    </div>
        
    <div class="col-md-12 form-group">
        <label for="">Password</label>
        <input class="form-control" type="password" name="password"/>
    </div>
        
    <button class="col-md-12 btn btn-primary mt-3" type="submit">Log In</button>
    <a class="col-md-12 btn btn-default mt-3" href="https://valentinragot.sites.3wa.io/php_avance/mvc/register">Register</a>
        
</form>
