<form method="post">

    <div class="col-md-12 form-group">
        <label for="">Firstname</label>
        <input class="form-control" type="text" name="firstname"/>
    </div>
    
    <div class="col-md-12 form-group">
        <label for="">Lastname</label>
        <input class="form-control" type="text" name="lastname"/>
    </div>

    <div class="col-md-12 form-group">
        <label for="">Email</label>
        <input class="form-control" type="text" name="email"/>
    </div>
        
    <div class="col-md-12 form-group">
        <label for="">Address</label>
        <input class="form-control" type="text" name="address"/>
    </div>
    
        <div class="col-md-12 form-group">
        <label for="">Postal Code</label>
        <input class="form-control" type="number" name="postalCode"/>
    </div>
    
        <div class="col-md-12 form-group">
        <label for="">Phone</label>
        <input class="form-control" type="number" name="phone"/>
    </div>
        
    <div class="col-md-12 form-group">
        <label for="">Password</label>
        <input class="form-control" type="password" name="password"/>
    </div>
        
    <button class="col-md-12 btn btn-primary mt-3" type="submit">Register</button>
    <a class="col-md-12 btn btn-default mt-3" href="https://valentinragot.sites.3wa.io/php_avance/mvc/login">Log In</a>
        
</form>
