version: "3.8"

services:
  server:
    restart: always
    build:
      context: ./server/
      dockerfile: Dockerfile
    command: "npm run start:dev"
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000

  mongodb:
    restart: always
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: irc
    volumes:
      - db_data:/data/db

  client:
    restart: always
    build:
      context: ./client/
      dockerfile: Dockerfile
    command: npm run dev
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 5173:5173

  mongo-gui:
    restart: always
    image: ugleiton/mongo-gui
    ports:
      - "4321:4321"
    environment:
      - MONGO_URL=mongodb://mongodb:27017/irc

volumes:
  db_data: {}
